### ISSUE TITLE
django-live-support and gunicorn

### ISSUE THREAD

**Issue by pierreNomazy** [MegaMark16/django-live-support#3]
Mark,
Thanks for you quick answer 'how it works ?' and it works with runserver. In production with gunicorn, we do not succeed having the 'admin-active' in the cache, so we are always with 'leave message'. Can you details how you app must be set up in a production environment ?
Pierre

**Comment by MegaMark16** [comment]
Do you have caching setup?  On my production environment where I'm using this I installed memcache and pointed my settings.py cache location at it.  Also, I've made some changes recently (to support support groups), are you using the most up to date version of django-live-support?

https://docs.djangoproject.com/en/dev/topics/cache/?from=olddocs

Let me know if that helps, and thanks for using this project!

Thanks
Mark

**Comment by pierreNomazy** [comment]
Mark,
We tried last version and we get an infinite loop : one message repeat himself with no end. so we use the previous version.
Pierre

**Comment by pierreNomazy** [comment]
We tried with gunicorn with and without cached; django-live-support can't work : no 'start chat' no chat at all. Do you have a life site as an example ? which development server do you use ?
Thanks
Pierre

**Comment by pierreNomazy** [comment]
With gunicorn the error message is : 2012-12-11 07:49:52 [6672] [INFO] Handling signal: winch
2012-12-11 07:49:52 [6672] [INFO] SIGWINCH ignored. Not daemonized

**Comment by MegaMark16** [comment]
I'm using it on http://www.djangolivesupport.com, although that site is still a work in progress, you can see what it's supposed to look like.  

Here is what my startup script looks like:  http://dpaste.com/845304/
Here is the output of pip freeze in my virtualenv: http://dpaste.com/845309/ (a lot of that is Django CMS related)
Here is a trimmed down version of my settings file: http://dpaste.com/845307/
And here is what my template looks like where I'm using the djangoliveesupport templatetag: http://dpaste.com/845308/

I'm using the current version of django-livesupport from github.

**Comment by ionics** [comment]
@pierreNomazy
Did you test with Chromium WebBrowser? If yes -> Dont do so... its not working on Chromium ... But it is working with Firefox 3.6.34 and 6.0.16.
So Chromium seems to break on javascript code...
details when I have them!

@MegaMark16 ->Thanks for the great app! Still needs some fixxes but is already much better than my solution!

**Comment by ionics** [comment]
@all special @MegaMark16 
add to the ajax call -> cache: false,
so Chromium (Chrome) and I think IE will also be able to keep a communication alive.

I am going to add a new issue now.

Greetings
ionic

**Comment by pierreNomazy** [comment]
the issue was set up of path of live_support/static  which is needed for a server in production and not for django runserver
